# Generated by Django 2.0.2 on 2018-03-04 06:40

from django.db import migrations, models
import django.db.models.deletion
import djobs.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=190, null=True)),
                ('code', models.CharField(default=djobs.core.models.new_code, max_length=190)),
            ],
        ),
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Only active job openings will be shown or printed.', verbose_name='Active')),
                ('public', models.BooleanField(default=False, help_text='If you set this option, we will publish the job posting both on our website and on a printed card at the conference venue. If you do not set it, we will only show it on a printed card at the conference venue, but not online.', verbose_name='This job posting should be shown online')),
                ('print_card', models.BooleanField(default=True, help_text='If you check this option, we will print a card for our physical job board for you. If you do not check it, you need to print and bring a card on your own. Please make sure to restrict yourself to a single A5-sized landscape page.', verbose_name='Please print a card for physical posting at the venue')),
                ('job_title', models.CharField(max_length=190, verbose_name='Job title')),
                ('job_location', models.CharField(max_length=190, verbose_name='Job location')),
                ('job_remote', models.BooleanField(default=False, verbose_name='Remote work possible')),
                ('job_salary_range', models.CharField(blank=True, max_length=190, null=True, verbose_name='Salary range (optional)')),
                ('job_description', models.TextField(verbose_name='Job description')),
                ('company_name', models.CharField(max_length=190, verbose_name='Company name')),
                ('company_description', models.TextField(blank=True, verbose_name='Company description')),
                ('company_contact', models.TextField(help_text='Preferrably, this should include a person to talk to directly at the conference, and also a contact option for after the conference.', verbose_name='Contact information')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Company logo')),
                ('access_code', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='job', to='core.AccessCode')),
            ],
        ),
    ]
