# Generated by Django 2.0.2 on 2018-03-04 06:45

from django.db import migrations, models
import djobs.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscode',
            name='code',
            field=models.CharField(default=djobs.core.models.new_code, max_length=190, unique=True),
        ),
    ]
